"""init

Revision ID: 655ef1e10514
Revises: ff1cc2150381
Create Date: 2025-11-21 08:15:10.776076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '655ef1e10514'
down_revision = 'ff1cc2150381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
