"""init

Revision ID: f95475c30f64
Revises: 8d854dae24b9
Create Date: 2025-11-21 08:16:10.932986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95475c30f64'
down_revision = '8d854dae24b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_method',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'EMAIL', 'LOCAL', name='authmethodenum'), nullable=False),
    sa.Column('provider_id', sa.String(length=150), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_auth_method')
    # ### end Alembic commands ###
